security:
  oauth2:
    client:
      client-id: 87d762db-dfe3-447a-b5b4-1d9cd697e6bc
      client-secret: MGFmYTJlMTctMmI1ZS00YzA1LWFiODgtN2VhNGJmNjAwZWYz
      access-token-uri: https://us-south.appid.cloud.ibm.com/oauth/v4/8f72b43f-2b8a-452c-8941-c3ae62f67ea6/token
      user-authorization-uri: https://us-south.appid.cloud.ibm.com/oauth/v4/8f72b43f-2b8a-452c-8941-c3ae62f67ea6/authorization
    resource:      user-info-uri: https://us-south.appid.cloud.ibm.com/oauth/v4/8f72b43f-2b8a-452c-8941-c3ae62f67ea6/userinfo

